import itemsModel from '../models/items.model.js';
import { generateTags, generateSummary, embeddingService, vectorStoreService } from '../services/aiService.js';
import { ContentExtractor } from '../services/contentExtractor.js';
import { getRedis, getJobFromQueue, updateJobStatus } from '../config/redis.js';

let isRunning = false;

// Utility to add timeout to promises
const withTimeout = (promise, timeoutMs, label) => {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`${label} timeout after ${timeoutMs}ms`)), timeoutMs)
    )
  ]);
};

export const startWorker = async () => {
  if (isRunning) {
    console.log('⚠️ Worker is already running');
    return;
  }
  
  isRunning = true;
  console.log('🤖 Redis Queue Worker started, listening for jobs...');
  console.log('⏳ Worker waiting for jobs on ai-processing:queue (will block until job arrives)...\n');

  while (isRunning) {
    try {
      // Wait for next job (blocking indefinitely)
      const job = await getJobFromQueue();
      
      if (!job) {
        console.log('⏰ Job retrieval returned null, waiting for next job...');
        continue;
      }

      const { jobId, itemId, title, url, notes, userProvidedTags } = job;

      console.log(`\n🚀 Processing Job ${jobId} for item ${itemId}`);

      try {
        // Step 1: Extract content from URL (with 30s timeout)
        console.log('📄 Step 1: Extracting content from URL...');
        await updateJobStatus(jobId, 'processing', 5);
        
        let extractedData = null;
        try {
          extractedData = await withTimeout(
            ContentExtractor.extractContent(url),
            30000,
            'Content extraction'
          );
        } catch (extractError) {
          console.warn('⚠️ Content extraction failed or timed out:', extractError.message);
          extractedData = {
            title: title || 'Untitled',
            content: notes || '',
            description: 'Content extraction failed',
            success: false
          };
        }

        console.log(`✅ Content extracted: ${extractedData.title.substring(0, 50)}... (${extractedData.content.length} chars)`);
        await updateJobStatus(jobId, 'processing', 15);

        // Step 2: Generate AI summary (with 30s timeout)
        console.log('📝 Step 2: Generating AI summary...');
        let summary = '';
        try {
          summary = await withTimeout(
            generateSummary(extractedData.content, extractedData.title),
            30000,
            'Summary generation'
          );
        } catch (summaryError) {
          console.warn('⚠️ Summary generation failed or timed out:', summaryError.message);
          summary = extractedData.description || 'Summary generation failed';
        }

        console.log(`✅ Summary generated: ${summary.substring(0, 100)}...`);
        await updateJobStatus(jobId, 'processing', 25);

        // Step 3: Generate AI tags (with 30s timeout)
        console.log('🏷️ Step 3: Generating AI tags...');
        let aiTags = [];
        try {
          aiTags = await withTimeout(
            generateTags(`${extractedData.title} ${extractedData.content} ${summary}`),
            30000,
            'Tag generation'
          );
        } catch (tagError) {
          console.warn('⚠️ Tag generation failed or timed out:', tagError.message);
          aiTags = [];
        }
        
        await updateJobStatus(jobId, 'processing', 40);
        
        if (aiTags.length > 0) {
          console.log(`✅ Generated tags: ${aiTags.join(', ')}`);
        } else {
          console.log('⚠️ No tags generated by AI');
        }

        // Step 4: Generate embedding (with 30s timeout)
        console.log('🧠 Step 4: Generating embedding...');
        let embedding = null;
        try {
          embedding = await withTimeout(
            embeddingService(`${extractedData.title} ${extractedData.content} ${summary}`),
            30000,
            'Embedding generation'
          );
        } catch (embError) {
          console.warn('⚠️ Embedding generation failed or timed out:', embError.message);
          embedding = null;
        }
        
        await updateJobStatus(jobId, 'processing', 60);

        if (!embedding) {
          console.warn('⚠️ Failed to generate embedding, continuing...');
        } else {
          console.log(`✅ Embedding generated, dimension: ${embedding.length}`);
        }

        // Step 5: Store in vector database (with 30s timeout)
        console.log('🔍 Step 5: Storing vector in Pinecone...');
        let vectorStored = false;
        if (embedding) {
          try {
            vectorStored = await withTimeout(
              vectorStoreService(itemId, embedding, {
                title: extractedData.title,
                itemId,
                type: 'knowledge',
              }),
              30000,
              'Vector storage'
            );
          } catch (vecError) {
            console.warn('⚠️ Vector storage failed or timed out:', vecError.message);
            vectorStored = false;
          }
        }
        await updateJobStatus(jobId, 'processing', 80);

        if (vectorStored) {
          console.log('✅ Vector stored successfully');
        }

        // Step 6: Update item in database
        console.log('💾 Step 6: Updating item in database...');
        const mergedTags = [...new Set([...(Array.isArray(userProvidedTags) ? userProvidedTags : []), ...aiTags])];

        const updatedItem = await itemsModel.findByIdAndUpdate(
          itemId,
          {
            tags: mergedTags,
            content: extractedData.content, // Store extracted content
            description: summary, // Store AI summary in description field
            extractedTitle: extractedData.title, // Store extracted title separately
            processing: false,
            aiProcessedAt: new Date(),
            contentExtractedAt: new Date(),
          },
          { returnDocument: 'after' }
        );

        await updateJobStatus(jobId, 'completed', 100);

        console.log(`✅ Job ${jobId} completed! Item updated with content extraction, summary, and ${mergedTags.length} tags`);
        console.log('🗂️ Updated item document:', {
          title: updatedItem.title,
          contentLength: updatedItem.content?.length || 0,
          tagsCount: mergedTags.length,
          hasSummary: !!updatedItem.notes
        });
        console.log(`✨ Success:`, {
          itemId,
          tagsCount: mergedTags.length,
          vectorStored,
        });

      } catch (error) {
        console.error(`❌ Error processing job ${jobId}:`, error.message);
        console.error('Stack trace:', error.stack);
        
        try {
          // Mark item as failed
          await itemsModel.findByIdAndUpdate(itemId, {
            processing: false,
            processingError: error.message,
          });

          await updateJobStatus(jobId, 'failed', 0);
        } catch (updateError) {
          console.error(`❌ Failed to mark job ${jobId} as failed:`, updateError.message);
        }
      }

    } catch (error) {
      if (error.message && error.message.includes('Command timed out')) {
        // Socket timeout on blocking command - this is expected, connection will retry
        console.warn('⚠️ Socket timeout on BRPOP (expected for blocking), reconnecting...');
      } else {
        console.error('❌ Worker error:', error.message);
      }
      // Wait before retrying
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }
};

export const stopWorker = () => {
  isRunning = false;
  console.log('🛑 Worker stopped');
};

export default { startWorker, stopWorker };
