import itemsModel from '../models/items.model.js';
import { generateTags, embeddingService, vectorStoreService } from '../services/aiService.js';
import { getRedis, getJobFromQueue, updateJobStatus } from '../config/redis.js';

let isRunning = false;

// Utility to add timeout to promises
const withTimeout = (promise, timeoutMs, label) => {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`${label} timeout after ${timeoutMs}ms`)), timeoutMs)
    )
  ]);
};

export const startWorker = async () => {
  if (isRunning) {
    console.log('⚠️ Worker is already running');
    return;
  }
  
  isRunning = true;
  console.log('🤖 Redis Queue Worker started, listening for jobs...');
  console.log('⏳ Worker waiting for jobs on ai-processing:queue (will block until job arrives)...\n');

  while (isRunning) {
    try {
      // Wait for next job (blocking indefinitely)
      const job = await getJobFromQueue();
      
      if (!job) {
        console.log('⏰ Job retrieval returned null, waiting for next job...');
        continue;
      }

      const { jobId, itemId, title, url, notes, userProvidedTags } = job;

      console.log(`\n🚀 Processing Job ${jobId} for item ${itemId}`);

      try {
        // Step 1: Generate tags (with 30s timeout)
        console.log('📝 Step 1: Generating AI tags...');
        await updateJobStatus(jobId, 'processing', 10);
        
        let aiTags = [];
        try {
          aiTags = await withTimeout(
            generateTags(`${title} ${notes || ''}`),
            30000,
            'Tag generation'
          );
        } catch (tagError) {
          console.warn('⚠️ Tag generation failed or timed out:', tagError.message);
          aiTags = [];
        }
        
        await updateJobStatus(jobId, 'processing', 30);
        
        if (aiTags.length > 0) {
          console.log(`✅ Generated tags: ${aiTags.join(', ')}`);
        } else {
          console.log('⚠️ No tags generated by AI');
        }

        // Step 2: Generate embedding (with 30s timeout)
        console.log('🧠 Step 2: Generating embedding...');
        let embedding = null;
        try {
          embedding = await withTimeout(
            embeddingService(`${title} ${notes || ''}`),
            30000,
            'Embedding generation'
          );
        } catch (embError) {
          console.warn('⚠️ Embedding generation failed or timed out:', embError.message);
          embedding = null;
        }
        
        await updateJobStatus(jobId, 'processing', 60);

        if (!embedding) {
          console.warn('⚠️ Failed to generate embedding, continuing...');
        } else {
          console.log(`✅ Embedding generated, dimension: ${embedding.length}`);
        }

        // Step 3: Store in vector database (with 30s timeout)
        console.log('🔍 Step 3: Storing vector in Pinecone...');
        let vectorStored = false;
        if (embedding) {
          try {
            vectorStored = await withTimeout(
              vectorStoreService(itemId, embedding, {
                title,
                itemId,
                type: 'knowledge',
              }),
              30000,
              'Vector storage'
            );
          } catch (vecError) {
            console.warn('⚠️ Vector storage failed or timed out:', vecError.message);
            vectorStored = false;
          }
        }
        await updateJobStatus(jobId, 'processing', 80);

        if (vectorStored) {
          console.log('✅ Vector stored successfully');
        }

        // Step 4: Update item in database
        console.log('💾 Step 4: Updating item in database...');
        const mergedTags = [...new Set([...(Array.isArray(userProvidedTags) ? userProvidedTags : []), ...aiTags])];

        const updatedItem = await itemsModel.findByIdAndUpdate(
          itemId,
          {
            tags: mergedTags,
            processing: false,
            aiProcessedAt: new Date(),
          },
          { returnDocument: 'after' }
        );

        await updateJobStatus(jobId, 'completed', 100);

        console.log(`✅ Job ${jobId} completed! Item updated with ${mergedTags.length} tags`);
        console.log('🗂️ Updated item document:', updatedItem);
        console.log(`✨ Success:`, {
          itemId,
          tagsCount: mergedTags.length,
          vectorStored,
        });

      } catch (error) {
        console.error(`❌ Error processing job ${jobId}:`, error.message);
        console.error('Stack trace:', error.stack);
        
        try {
          // Mark item as failed
          await itemsModel.findByIdAndUpdate(itemId, {
            processing: false,
            processingError: error.message,
          });

          await updateJobStatus(jobId, 'failed', 0);
        } catch (updateError) {
          console.error(`❌ Failed to mark job ${jobId} as failed:`, updateError.message);
        }
      }

    } catch (error) {
      if (error.message && error.message.includes('Command timed out')) {
        // Socket timeout on blocking command - this is expected, connection will retry
        console.warn('⚠️ Socket timeout on BRPOP (expected for blocking), reconnecting...');
      } else {
        console.error('❌ Worker error:', error.message);
      }
      // Wait before retrying
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }
};

export const stopWorker = () => {
  isRunning = false;
  console.log('🛑 Worker stopped');
};

export default { startWorker, stopWorker };
